# Generated by Django 6.0.5 on 2026-05-12 19:04

import apps.patients.domain.enums
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tooth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'patients_tooth',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergies', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('archived', 'Архивный')], default=apps.patients.domain.enums.PatientStatus['ACTIVE'], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patients_patient',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено')], default=apps.patients.domain.enums.VisitStatus['PLANNED'], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient')),
            ],
            options={
                'db_table': 'patients_visit',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='SoapNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjective', models.TextField(blank=True, default='')),
                ('objective', models.TextField(blank=True, default='')),
                ('assessment', models.TextField(blank=True, default='')),
                ('plan', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='soap_note', to='patients.visit')),
            ],
            options={
                'db_table': 'patients_soap_note',
            },
        ),
        migrations.CreateModel(
            name='Odontogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='odontogram', to='patients.visit')),
            ],
            options={
                'db_table': 'patients_odontogram',
            },
        ),
        migrations.CreateModel(
            name='PatientTooth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('healthy', 'Здоровый'), ('caries', 'Кариес'), ('treated', 'Пролечен'), ('crown', 'Коронка'), ('extracted', 'Удалён'), ('implant', 'Имплант'), ('filling', 'Пломба')], default=apps.patients.domain.enums.ToothStatus['HEALTHY'], max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teeth', to='patients.patient')),
                ('tooth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.tooth')),
            ],
            options={
                'db_table': 'patients_patient_tooth',
                'ordering': ['tooth__number'],
                'unique_together': {('patient', 'tooth')},
            },
        ),
        migrations.CreateModel(
            name='OdontogramEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('healthy', 'Здоровый'), ('caries', 'Кариес'), ('treated', 'Пролечен'), ('crown', 'Коронка'), ('extracted', 'Удалён'), ('implant', 'Имплант'), ('filling', 'Пломба')], default=apps.patients.domain.enums.ToothStatus['HEALTHY'], max_length=20)),
                ('odontogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='patients.odontogram')),
                ('tooth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.tooth')),
            ],
            options={
                'db_table': 'patients_odontogram_entry',
                'ordering': ['tooth__number'],
                'unique_together': {('odontogram', 'tooth')},
            },
        ),
        migrations.CreateModel(
            name='VisitTooth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.tooth')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_teeth', to='patients.visit')),
            ],
            options={
                'db_table': 'patients_visit_tooth',
                'ordering': ['tooth__number'],
                'unique_together': {('visit', 'tooth')},
            },
        ),
    ]
